[package]
name = "slow"
version = "0.1.0"
authors = ["Jan Mazur <mzr4141@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.5"
argparse = "0.2.2"
